export const locations: Location[] = [
  {
    name: "Hyundai Santacruz",
    type: "Showroom",
    city: "Mumbai",
    address: "Hyundai Santacruz Showroom",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/03/Untitled-design-24-300x150.png",
  },
  {
    name: "Hyundai Vasai",
    type: "Showroom",
    city: "Vasai",
    address: "Prime House Main Rd, Sativali Rd, Opp Shailesh Industries Estate, Waliv Phata, Vasai East, Maharashtra 401208",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/02/Hyundai-Vasai-Showroom-scaled.png",
  },
  {
    name: "Hyundai Virar",
    type: "Showroom",
    city: "Virar",
    address: "HDL Residency Park, Shop 1/2 E Wing, Global City, Opp Yazoo Park, Virar West, Mumbai, Maharashtra 401305",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/02/Hyundai-Virar-Showroom-scaled.png",
  },
  {
    name: "Hyundai Thane",
    type: "Showroom",
    city: "Thane",
    address: "Modi House 1 Eastern Express Highway opp LIC Bldg., Naupada, Louis Wadi, Thane West, Maharashtra 400602",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/02/Hyundai-Thane-Showroom-scaled.png",
  },
  {
    name: "Hyundai H Promise Thane",
    type: "Showroom",
    city: "Thane",
    address: "Wadekar Compound, Modi Hyundai H Promise Showroom, near Viddyapith Bus Stop, Service Rd, Thane West - 400601",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/03/Untitled-design-30.png",
  },
  {
    name: "Hyundai Wada",
    type: "Showroom",
    city: "Wada",
    address: "HDL Residency Park , Shop No. 1/2, E Wing Global City , Opp Yazoo Park Virar, Virar West, Maharashtra 401305",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/02/Hyundai-Service-and-sales-Wada-scaled.png",
  },
  {
    name: "Hyundai Service Centre Wada",
    type: "Service Centre",
    city: "Wada",
    address: "Hyundai Service Centre Wada",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/03/Untitled-design-24-300x150.png",
  },
  {
    name: "Hyundai Service Centre Chunabhatti",
    type: "Service Centre",
    city: "Mumbai",
    address: "Jogani Industrial Estate, VN Purav Marg, Panchsheel Nagar, Chunabhatti, Sion, Mumbai, Maharashtra 400022",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/02/Hyundai-Service-Chunnabhatti-scaled.png",
  },
  {
    name: "Hyundai Service Centre Thane",
    type: "Service Centre",
    city: "Thane",
    address: "Navjeevan Compound, 2, Pokhran Rd, opp. Oswal Park, Subhash Nagar, Majiwada, Thane, Maharashtra 400601",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/02/Hyundai-Thane-Service-scaled.png",
  },
  {
    name: "Hyundai Service Centre Vasai",
    type: "Service Centre",
    city: "Vasai",
    address: "Gala No 8, Richa Industrial Estate, Sativali Rd, Waliv Phata, Golani Naka, Vasai East, Maharashtra 401208",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/02/Hyundai-Vasai-Service-scaled.png",
  },
  {
    name: "Hyundai Service Centre Virar",
    type: "Service Centre",
    city: "Virar",
    address: "Sanjog Industrial Estate, Gala no 18,19, near Ran Pada Ground, Virar West, Virar, Maharashtra 401303",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/02/Hyundai-Virar-Service-scaled.png",
  },
  {
    name: "Hyundai Service Centre Thane (Raghunath Nagar)",
    type: "Service Centre",
    city: "Thane",
    address: "ICEM Engineering Compound Mohanji, Road, opposite Valencia Park, Raghunath Nagar, Sunderji, Thane, Maharashtra 400604",
    phone: "98877 33000",
    image: "https://bunny-wp-pullzone-cghvklkcns.b-cdn.net/wp-content/uploads/2026/02/Hyundai-raghunath-nagar-service-scaled.png",
  },
];